package edu.gatech.group16.watersourcingproject.model;

import android.location.Location;

import java.util.Arrays;
import java.util.Date;
import java.util.List;

import edu.gatech.group16.watersourcingproject.model.Enums.WaterQuality;
import edu.gatech.group16.watersourcingproject.model.Enums.WaterType;

/**
 * Created by Edwin Zhao on 2017/02/23.
 * Date and time of report (can be autogenerated by application)
 */

public class WaterSourceReport {
    public static List<WaterType> legalTypes = Arrays.asList(WaterType.values());
    public static List<WaterQuality> legalQuality = Arrays.asList(WaterQuality.values());

    private int reportNumber;
    private Date date;
    private Location location;
    private WaterType waterType;
    private WaterQuality waterQuality;
    private String submittedBy;


    public WaterSourceReport() {

    }

    public WaterSourceReport(int reportNumber, Date date, Location location,
                             WaterType waterType, WaterQuality waterQuality,
                             String submittedBy) {
        this.reportNumber = reportNumber;
        this.date = date;
        this.location = location;
        this.waterType = waterType;
        this.waterQuality = waterQuality;
        this.submittedBy = submittedBy;
    }



    public String getSubmittedBy() {
        return submittedBy;
    }

    public void setSubmittedBy(String submittedBy) {
        this.submittedBy = submittedBy;
    }

    public int getReportNumber() {
        return reportNumber;
    }

    public void setReportNumber(int reportNumber) {
        this.reportNumber = reportNumber;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Location getLocation() {
        return location;
    }

    public void setLocation(Location location) {
        this.location = location;
    }

    public WaterType getWaterType() {
        return waterType;
    }

    public void setWaterType(WaterType waterType) {
        this.waterType = waterType;
    }

    public WaterQuality getWaterQuality() {
        return waterQuality;
    }

    public void setWaterQuality(WaterQuality waterQuality) {
        this.waterQuality = waterQuality;
    }

    @Override
    public String toString() {
        return "WaterSourceReport{" +
                "reportNumber=" + reportNumber +
                ", date=" + date +
                ", location=" + location +
                ", waterType=" + waterType +
                ", waterQuality=" + waterQuality +
                ", submittedBy='" + submittedBy + '\'' +
                '}';
    }


}
