package edu.gatech.group16.watersourcingproject.model;

import android.location.Location;

import java.io.Serializable;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

import edu.gatech.group16.watersourcingproject.model.Enums.WaterCondition;
import edu.gatech.group16.watersourcingproject.model.Enums.WaterType;

/**
 * Created by Edwin Zhao on 2017/02/23.
 * Date and time of report (can be autogenerated by application)
 */

public class WaterSourceReport implements Serializable {
    public static List<WaterType> legalTypes = Arrays.asList(WaterType.values());
    public static List<WaterCondition> legalConditions = Arrays.asList(WaterCondition.values());

    private int reportNumber;
    private Date date;
    private String location;
    private WaterType waterType;
    private WaterCondition waterCondition;
    private String submittedBy;


    public WaterSourceReport() {

    }

    public WaterSourceReport(int reportNumber, Date date, String location,
                             WaterType waterType, WaterCondition waterCondition,
                             String submittedBy) {
        this.reportNumber = reportNumber;
        this.date = date;
        this.location = location;
        this.waterType = waterType;
        this.waterCondition = waterCondition;
        this.submittedBy = submittedBy;
    }



    public String getSubmittedBy() {
        return submittedBy;
    }

    public void setSubmittedBy(String submittedBy) {
        this.submittedBy = submittedBy;
    }

    public int getReportNumber() {
        return reportNumber;
    }

    public void setReportNumber(int reportNumber) {
        this.reportNumber = reportNumber;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public WaterType getWaterType() {
        return waterType;
    }

    public void setWaterType(WaterType waterType) {
        this.waterType = waterType;
    }

    public WaterCondition getWaterCondition() {
        return waterCondition;
    }

    public void setWaterCondition(WaterCondition waterCondition) { this.waterCondition = waterCondition; }

    @Override
    public String toString() {
        return "WaterSourceReport{" +
                "reportNumber=" + reportNumber +
                ", date=" + date +
                ", location=" + location +
                ", waterType=" + waterType +
                ", waterCondition=" + waterCondition +
                ", submittedBy='" + submittedBy + '\'' +
                '}';
    }


}
